#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BlockChainVotingsAndroid.Resource", IsApplication=true)]

namespace BlockChainVotingsAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::NetworkCommsDotNet.Resource.String.ApplicationName = global::BlockChainVotingsAndroid.Resource.String.ApplicationName;
			global::NetworkCommsDotNet.Resource.String.Hello = global::BlockChainVotingsAndroid.Resource.String.Hello;
			global::ProtobufSerializer.Resource.String.ApplicationName = global::BlockChainVotingsAndroid.Resource.String.ApplicationName;
			global::ProtobufSerializer.Resource.String.Hello = global::BlockChainVotingsAndroid.Resource.String.Hello;
			global::SharpZipLibCompressor.Resource.String.ApplicationName = global::BlockChainVotingsAndroid.Resource.String.ApplicationName;
			global::SharpZipLibCompressor.Resource.String.Hello = global::BlockChainVotingsAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050015
			public const int SCROLLER_ID = 2131034133;
			
			// aapt resource value: 0x7f050004
			public const int buttonLogin = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int buttonReg = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int buttonStart = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int buttonStop = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int checkBoxCreateBlocks = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int editTextPass2Reg = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int editTextPassLogin = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int editTextPassReg = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int editTextPrivateKeyReg = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int editTextPublicKeyLogin = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int editTextPublicKeyReg = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int editTextTrackers = 2131034127;
			
			// aapt resource value: 0x7f050017
			public const int textView1 = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int textViewConsole = 2131034134;
			
			// aapt resource value: 0x7f050014
			public const int textViewConsoleLabel = 2131034132;
			
			// aapt resource value: 0x7f050010
			public const int textViewNetConnection = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int textViewPass2Reg = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int textViewPassLogin = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int textViewPassReg = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int textViewPrivateKeyReg = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int textViewPublicKeyLogin = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int textViewPublicKeyReg = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int textViewTrackers = 2131034126;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Setting = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Voting = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int blockChainVoting = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int console = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int createBlocks = 2130968591;
			
			// aapt resource value: 0x7f040007
			public const int login = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int netConnection = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int password = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int password2 = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int privateKey = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int publicKey = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int register = 2130968582;
			
			// aapt resource value: 0x7f040011
			public const int setting = 2130968593;
			
			// aapt resource value: 0x7f04000b
			public const int start = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int stop = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int toLogin = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int toRegister = 2130968584;
			
			// aapt resource value: 0x7f040012
			public const int trackers = 2130968594;
			
			// aapt resource value: 0x7f040010
			public const int voting = 2130968592;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
