#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BlockChainVotingsAndroid.Resource", IsApplication=true)]

namespace BlockChainVotingsAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::NetworkCommsDotNet.Resource.String.ApplicationName = global::BlockChainVotingsAndroid.Resource.String.ApplicationName;
			global::NetworkCommsDotNet.Resource.String.Hello = global::BlockChainVotingsAndroid.Resource.String.Hello;
			global::ProtobufSerializer.Resource.String.ApplicationName = global::BlockChainVotingsAndroid.Resource.String.ApplicationName;
			global::ProtobufSerializer.Resource.String.Hello = global::BlockChainVotingsAndroid.Resource.String.Hello;
			global::SharpZipLibCompressor.Resource.String.ApplicationName = global::BlockChainVotingsAndroid.Resource.String.ApplicationName;
			global::SharpZipLibCompressor.Resource.String.Hello = global::BlockChainVotingsAndroid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int buttonLogin = 2131034116;
			
			// aapt resource value: 0x7f05000d
			public const int buttonReg = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int buttonStart = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int buttonStop = 2131034131;
			
			// aapt resource value: 0x7f050026
			public const int buttonVote = 2131034150;
			
			// aapt resource value: 0x7f050025
			public const int checkBoxAgree = 2131034149;
			
			// aapt resource value: 0x7f050014
			public const int checkBoxCreateBlocks = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int checkBoxPeerDiscovery = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int checkBoxUseLanLocalIP = 2131034134;
			
			// aapt resource value: 0x7f05000c
			public const int editTextPass2Reg = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int editTextPassLogin = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int editTextPassReg = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int editTextPrivateKeyReg = 2131034120;
			
			// aapt resource value: 0x7f050001
			public const int editTextPublicKeyLogin = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int editTextPublicKeyReg = 2131034118;
			
			// aapt resource value: 0x7f05000f
			public const int editTextTrackers = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout1 = 2131034129;
			
			// aapt resource value: 0x7f050017
			public const int scrollVIewConsole = 2131034135;
			
			// aapt resource value: 0x7f050024
			public const int spinnerCandidates = 2131034148;
			
			// aapt resource value: 0x7f050022
			public const int spinnerVoting = 2131034146;
			
			// aapt resource value: 0x7f050019
			public const int textView1 = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int textViewBlocks = 2131034139;
			
			// aapt resource value: 0x7f050018
			public const int textViewConsole = 2131034136;
			
			// aapt resource value: 0x7f050020
			public const int textViewHello = 2131034144;
			
			// aapt resource value: 0x7f050010
			public const int textViewNetConnection = 2131034128;
			
			// aapt resource value: 0x7f05000b
			public const int textViewPass2Reg = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int textViewPassLogin = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int textViewPassReg = 2131034121;
			
			// aapt resource value: 0x7f05001f
			public const int textViewPeers = 2131034143;
			
			// aapt resource value: 0x7f050007
			public const int textViewPrivateKeyReg = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int textViewPublicKeyLogin = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int textViewPublicKeyReg = 2131034117;
			
			// aapt resource value: 0x7f050023
			public const int textViewSelectCandidate = 2131034147;
			
			// aapt resource value: 0x7f050021
			public const int textViewSelectVoting = 2131034145;
			
			// aapt resource value: 0x7f05000e
			public const int textViewTrackers = 2131034126;
			
			// aapt resource value: 0x7f05001a
			public const int textViewTransactions = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int textViewUsers = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int textViewVotings = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int view1 = 2131034142;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Register = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Setting = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Statistics = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Voting = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040017
			public const int agree = 2130968599;
			
			// aapt resource value: 0x7f04000a
			public const int blockChainVoting = 2130968586;
			
			// aapt resource value: 0x7f04001f
			public const int blocks = 2130968607;
			
			// aapt resource value: 0x7f04000e
			public const int console = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int createBlocks = 2130968591;
			
			// aapt resource value: 0x7f040015
			public const int from = 2130968597;
			
			// aapt resource value: 0x7f04001a
			public const int hello = 2130968602;
			
			// aapt resource value: 0x7f040007
			public const int login = 2130968583;
			
			// aapt resource value: 0x7f04000d
			public const int netConnection = 2130968589;
			
			// aapt resource value: 0x7f040025
			public const int newVoting = 2130968613;
			
			// aapt resource value: 0x7f040024
			public const int noCandidates = 2130968612;
			
			// aapt resource value: 0x7f040004
			public const int password = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int password2 = 2130968581;
			
			// aapt resource value: 0x7f040019
			public const int peerDiscovery = 2130968601;
			
			// aapt resource value: 0x7f040022
			public const int peers = 2130968610;
			
			// aapt resource value: 0x7f040003
			public const int privateKey = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int publicKey = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int register = 2130968582;
			
			// aapt resource value: 0x7f040014
			public const int selectCandidate = 2130968596;
			
			// aapt resource value: 0x7f040013
			public const int selectVoting = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int setting = 2130968593;
			
			// aapt resource value: 0x7f040016
			public const int snils = 2130968598;
			
			// aapt resource value: 0x7f04000b
			public const int start = 2130968587;
			
			// aapt resource value: 0x7f040023
			public const int statistics = 2130968611;
			
			// aapt resource value: 0x7f04000c
			public const int stop = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int toLogin = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int toRegister = 2130968584;
			
			// aapt resource value: 0x7f040012
			public const int trackers = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int transactions = 2130968606;
			
			// aapt resource value: 0x7f04001d
			public const int useLanLocalIP = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public const int user = 2130968604;
			
			// aapt resource value: 0x7f040020
			public const int users = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int vote = 2130968600;
			
			// aapt resource value: 0x7f04001b
			public const int voteComplete = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int voting = 2130968592;
			
			// aapt resource value: 0x7f040021
			public const int votings = 2130968609;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
