//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlockChainVotings.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlockChainVotings.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copyright © 2016 Maxim Kuzmin, ISPU.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активный.
        /// </summary>
        internal static string active {
            get {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждаю.
        /// </summary>
        internal static string agree {
            get {
                return ResourceManager.GetString("agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ↓.
        /// </summary>
        internal static string arrowDown {
            get {
                return ResourceManager.GetString("arrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ↑.
        /// </summary>
        internal static string arrowUp {
            get {
                return ResourceManager.GetString("arrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во выдвижений.
        /// </summary>
        internal static string asCandidate {
            get {
                return ResourceManager.GetString("asCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доступно.
        /// </summary>
        internal static string avaliableN {
            get {
                return ResourceManager.GetString("avaliableN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое голосование.
        /// </summary>
        internal static string avaliableNewVoting {
            get {
                return ResourceManager.GetString("avaliableNewVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокировать.
        /// </summary>
        internal static string ban {
            get {
                return ResourceManager.GetString("ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заблокирован.
        /// </summary>
        internal static string banned {
            get {
                return ResourceManager.GetString("banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Блокировка пользователя.
        /// </summary>
        internal static string banUser {
            get {
                return ResourceManager.GetString("banUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Блоки.
        /// </summary>
        internal static string blocks {
            get {
                return ResourceManager.GetString("blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хеш кандидата.
        /// </summary>
        internal static string candidateHash {
            get {
                return ResourceManager.GetString("candidateHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя кандидата.
        /// </summary>
        internal static string candidateName {
            get {
                return ResourceManager.GetString("candidateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кандидаты.
        /// </summary>
        internal static string candidates {
            get {
                return ResourceManager.GetString("candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина.
        /// </summary>
        internal static string cause {
            get {
                return ResourceManager.GetString("cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сменить оформление.
        /// </summary>
        internal static string changeTheme {
            get {
                return ResourceManager.GetString("changeTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор кандидата.
        /// </summary>
        internal static string chooseCandidate {
            get {
                return ResourceManager.GetString("chooseCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор голосования.
        /// </summary>
        internal static string chooseVoting {
            get {
                return ResourceManager.GetString("chooseVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подкл. пиры.
        /// </summary>
        internal static string connectedPeers {
            get {
                return ResourceManager.GetString("connectedPeers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подкл. трекеры.
        /// </summary>
        internal static string connectedTrackers {
            get {
                return ResourceManager.GetString("connectedTrackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Консоль.
        /// </summary>
        internal static string console {
            get {
                return ResourceManager.GetString("console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать хеш кандидата.
        /// </summary>
        internal static string copyCandidate {
            get {
                return ResourceManager.GetString("copyCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать хеш.
        /// </summary>
        internal static string copyHash {
            get {
                return ResourceManager.GetString("copyHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать хеш голосования.
        /// </summary>
        internal static string copyVoting {
            get {
                return ResourceManager.GetString("copyVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создавать свои блоки.
        /// </summary>
        internal static string createBlocks {
            get {
                return ResourceManager.GetString("createBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание пользователя.
        /// </summary>
        internal static string createUser {
            get {
                return ResourceManager.GetString("createUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание голосования.
        /// </summary>
        internal static string createVoting {
            get {
                return ResourceManager.GetString("createVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на от.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Генерировать ключи.
        /// </summary>
        internal static string generateKeys {
            get {
                return ResourceManager.GetString("generateKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привет.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В голосовании.
        /// </summary>
        internal static string inVoting {
            get {
                return ResourceManager.GetString("inVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на и проголосовать за кандидата.
        /// </summary>
        internal static string iVoteFor {
            get {
                return ResourceManager.GetString("iVoteFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посл. активность.
        /// </summary>
        internal static string lastActivity {
            get {
                return ResourceManager.GetString("lastActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка загрузки требуемых библиотек. Проверьте правильность установки программы..
        /// </summary>
        internal static string libsError {
            get {
                return ResourceManager.GetString("libsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход в сеть.
        /// </summary>
        internal static string loginIntoNet {
            get {
                return ResourceManager.GetString("loginIntoNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Главная.
        /// </summary>
        internal static string main {
            get {
                return ResourceManager.GetString("main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Моя статистика.
        /// </summary>
        internal static string myStatistic {
            get {
                return ResourceManager.GetString("myStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение к сети.
        /// </summary>
        internal static string netConnection {
            get {
                return ResourceManager.GetString("netConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика сети.
        /// </summary>
        internal static string netStatistic {
            get {
                return ResourceManager.GetString("netStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на голосований.
        /// </summary>
        internal static string nVotings {
            get {
                return ResourceManager.GetString("nVotings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки.
        /// </summary>
        internal static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string pass {
            get {
                return ResourceManager.GetString("pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повтор пароля.
        /// </summary>
        internal static string passRepeat {
            get {
                return ResourceManager.GetString("passRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружение пиров.
        /// </summary>
        internal static string peerDiscovery {
            get {
                return ResourceManager.GetString("peerDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Секретный ключ.
        /// </summary>
        internal static string privateKey {
            get {
                return ResourceManager.GetString("privateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата регистр..
        /// </summary>
        internal static string regDate {
            get {
                return ResourceManager.GetString("regDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        internal static string registration {
            get {
                return ResourceManager.GetString("registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск пользователей.
        /// </summary>
        internal static string searchUser {
            get {
                return ResourceManager.GetString("searchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голосование.
        /// </summary>
        internal static string sendVote {
            get {
                return ResourceManager.GetString("sendVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоп.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять участие в голосовании.
        /// </summary>
        internal static string takePatrInVoting {
            get {
                return ResourceManager.GetString("takePatrInVoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        internal static string toLogin {
            get {
                return ResourceManager.GetString("toLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Трекеры.
        /// </summary>
        internal static string trackers {
            get {
                return ResourceManager.GetString("trackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакции.
        /// </summary>
        internal static string transactions {
            get {
                return ResourceManager.GetString("transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Локальный IP.
        /// </summary>
        internal static string useLanLocalIP {
            get {
                return ResourceManager.GetString("useLanLocalIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на пользователь.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хеш.
        /// </summary>
        internal static string userHash {
            get {
                return ResourceManager.GetString("userHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СНИЛС.
        /// </summary>
        internal static string userID {
            get {
                return ResourceManager.GetString("userID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация о пользователе.
        /// </summary>
        internal static string userInfo {
            get {
                return ResourceManager.GetString("userInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО.
        /// </summary>
        internal static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика пользователей.
        /// </summary>
        internal static string usersStatistics {
            get {
                return ResourceManager.GetString("usersStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string userStatus {
            get {
                return ResourceManager.GetString("userStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голосования пользователя.
        /// </summary>
        internal static string userVotings {
            get {
                return ResourceManager.GetString("userVotings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голосовать.
        /// </summary>
        internal static string vote {
            get {
                return ResourceManager.GetString("vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата голосования.
        /// </summary>
        internal static string voteDate {
            get {
                return ResourceManager.GetString("voteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на голосов.
        /// </summary>
        internal static string votes {
            get {
                return ResourceManager.GetString("votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голоса.
        /// </summary>
        internal static string votesCount {
            get {
                return ResourceManager.GetString("votesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хеш голосования.
        /// </summary>
        internal static string votingHash {
            get {
                return ResourceManager.GetString("votingHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon votingIcon {
            get {
                object obj = ResourceManager.GetObject("votingIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string votingName {
            get {
                return ResourceManager.GetString("votingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Голосования.
        /// </summary>
        internal static string votings {
            get {
                return ResourceManager.GetString("votings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во голосований.
        /// </summary>
        internal static string votingsCount {
            get {
                return ResourceManager.GetString("votingsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Система электронных голосований.
        /// </summary>
        internal static string votingSoftware {
            get {
                return ResourceManager.GetString("votingSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статистика голосований.
        /// </summary>
        internal static string votingsStatistics {
            get {
                return ResourceManager.GetString("votingsStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для голосования загружены не все кандидаты. Дождитесь синхронизации базы данных..
        /// </summary>
        internal static string waitDB {
            get {
                return ResourceManager.GetString("waitDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на с результатом.
        /// </summary>
        internal static string withResult {
            get {
                return ResourceManager.GetString("withResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на одерживает победу кандидат.
        /// </summary>
        internal static string wons {
            get {
                return ResourceManager.GetString("wons", resourceCulture);
            }
        }
    }
}
